### ISSUE TITLE
Fit_p_value bug

### ISSUE THREAD

**Issue by balaram26** [mdfeatureselection/mdfs-py#3] opened 2023-09-12 14:56 UTC
The fit_p_value doesn't work the way it should. The results from python/cpp doesn't match the R package values. The issue seems to be arising from the alpha calculation as the alpha doesn't match between the two. 

Possible source: The R package does sorting of the input before calculating the inputs, but the fitpvalue code doesn't seem to perform such operations, also the code does the analysis on the cpp part. Another possibility for the bug could be the contrast variable part.

**Comment by balaram26** [comment] 2023-09-13 12:40
The contrast variable seems the secondary reason for the results mismatch. The fit_p_value cal is based on chisq_contrast, but this is generated using "generatecontrastvariable" function, and this function gives me diff set of vars for same data and config every time I run it. And by default, the fit_p cpp function cannot work without contrast_var like the R function.  Once  this is fixed, the input parts for the fit_p_value is all okay, but the calcS alpha calculation is still not okay.  Alpha calculation is still doesn't match.

**Comment by yoctozepto** [comment] 2023-09-13 13:09
The fitting is only on contrast variables by design. The generation of contrast variables is seeded so it is possible to get the same results every time after setting the same seed.

Where is that sorting bug that you mention?
(please link to code)

**Comment by balaram26** [comment] 2023-09-13 13:51
There must b some issue with the contrast vars, as their inputs SV variable don't match at fit_p_value step. If there is no issue with contrast variables, then there won't be such a difference in the fit_p_value(SV variable data) between the R and python/cpp versions. the SV var uses the V var, which uses the contrast variable data. with the input conditions being the same, the inputs printed by R and Python should not be different. i have attached the outputs of the Sv variable that's used for the alpha calculation here:

R version:
`0.03956065,0.07633239,0.10840206,0.13975801,0.16985833,0.19984934,0.22923746,0.25785023,0.2864267,0.31364384,0.34074378,0.36756088,0.39283147,0.41789339,0.44281574,0.46730953,0.49133125,0.51501192,0.53734963,0.55943176,0.58125755,0.60184906,0.62199593,0.6417863,0.66141656,0.68095734,0.70039424,0.71910655,0.73781412,0.75622645,0.7745533,0.7925711,0.81056604,0.82851232,0.84614702,0.86373552,0.88122164,0.89870479,0.91563332,0.93242206,0.94913992,0.96463327,0.98006905,0.99546569,1.01076883,1.02603058,1.0410337,1.05579006,1.07043075,1.08491129,1.0989562,1.11277712,1.12620157,1.13936505,1.15252743,1.1654394,1.17831428,1.19114784,1.20392721,1.21668606,1.22932884,1.24178264,1.25421959,1.2665695,1.27883402,1.29092544,1.30294748,1.31494006,1.32681451,1.33857496,1.35032945,1.36193864,1.3734432,1.38490113,1.39632905,1.40759948,1.41881189,1.43001766,1.44104752,1.45206526,1.46304112,1.47401235,1.48491232,1.49573236,1.50653044,1.51732669,1.52807737,1.53870145,1.54927352,1.55978137,1.57018924,1.58058567,1.59087271,1.60108604,1.61123648,1.62137404,1.63145429,1.6415192,1.65148075,1.66144062,1.67135005,1.68112623,1.69089827,1.70065792,1.71035009,1.71999644,1.72964034,1.73917229,1.74865919,1.75811803,1.76756487,1.77700532,1.78637336,1.79561074,1.80482392,1.81401841,1.82312001,1.83216634,1.84118592,1.85018491,1.85917401,1.86804599,1.87672272,1.88537599,1.89399929,1.90253548,1.91105579,1.91957394,1.92807481,1.93654409,1.94495553,1.95334351,1.96171164,1.97001137,1.97812913,1.98616692,1.99419113,2.00217335,2.01012658,2.01801214,2.02588302,2.03367967,2.04144275,2.04917568,2.0569086,2.06463825,2.07235483,2.08003884,2.08766197,2.09521129,2.10270967,2.11017261,2.11753832,2.12486486,2.13218707,2.139487,2.14675735,2.15369535,2.16061752,2.16748427,2.17433187,2.18115807,2.18798369,2.19480873,2.20162858,2.20841102,2.21518027,2.22186812,2.22854691,2.23508315,2.24155445,2.2480088,2.25443535,2.26084399,2.26722557,2.2736023,2.27989594,2.28616407,2.2923994,2.29862314,2.30481956,2.31094197,2.31704421,2.32312377,2.3291409,2.33514024,2.34111071,2.34705195,2.35295661,2.35885627,2.36471069,2.37054433,2.37632442,2.38209864,2.3877611,2.39340682,2.39905253,2.40469491,2.41030301,2.41588791,2.42146525,2.4270327,2.43257241,2.43805849,2.44353714,2.44899221,2.45429392,2.45959383,2.46486468,2.47013509,2.47538724,2.4806385,2.485876,2.49105753,2.49618454,2.50127869,2.50625989,2.51121293,2.5161509,2.52106137,2.52592883,2.53067589,2.53538494,2.54008802,2.54476689,2.54943311,2.55405493,2.5586744,2.56324372,2.56780455,2.57235112,2.57686587,2.58137719,2.58588697,2.59036899,2.59479636,2.59921811,2.6036026,2.60790514,2.61219714,2.61644541,2.62068938,2.62493083,2.62915903,2.63337436,2.63756587,2.64173474,2.64584651,2.6499482,2.65404885,2.65809641,2.66212416,2.66614782,2.67013623,2.67410377,2.67797187,2.68183506,2.68566052,2.68948275,2.69329786,2.6970943,2.70084476,2.70458382,2.708303,2.71197402,2.71561012,2.7192104,2.72279973,2.72637239,2.72992877,2.73341572,2.73688179,2.74030443,2.74372475,2.74713959,2.75053799,2.7539315,2.75731814,2.76068848,2.76405084,2.76737614,2.77067789,2.77396848,2.77725824,2.78052581,2.78377572,2.78694311,2.79008089,2.79313227,2.79613702,2.7991306,2.80209244,2.80504902,2.80799985,2.81092805,2.81384932,2.81674671,2.81964165,2.82252851,2.82540271,2.82824113,2.83107284,2.83389976,2.83672429,2.83954834,2.84233207,2.84510052,2.84786757,2.85058496,2.85321972,2.85585403,2.85847655,2.86108999,2.86368207,2.86627196,2.86881881,2.87134293,2.87386278,2.87637795,2.87885447,2.88130804,2.88375043,2.88617183,2.88856736,2.89095418,2.89333979,2.89571031,2.89806703,2.90039088,2.90270179,2.90495554,2.90719579,2.90942715,2.9116536,2.91387047,2.91600831,2.91814019,2.92027135,2.92239334,2.92450958,2.92659543,2.92867704,2.93074549,2.93279859,2.93484545,2.93688522,2.93885778,2.94082517,2.94277598,2.94472201,2.9466577,2.94857561,2.95049029,2.95238417,2.95423873,2.9560772,2.9579028,2.95969504,2.96148622,2.96327058,2.96504276,2.96679289,2.9685006,2.97017979,2.9718577,2.9735023,2.97510785,2.97670446,2.97829339,2.9798668,2.98142682,2.98297069,2.98451417,2.986057,2.98759643,2.98912911,2.99065971,2.99218992,2.9937093,2.9952197,2.99671764,2.99817075,2.99959381,3.0010025,3.00239671,3.00378246,3.00515514,3.00647341,3.00778578,3.00908413,3.01037852,3.01165768,3.01292348,3.01417851,3.01542972,3.01666956,3.01789189,3.01911092,3.02029057,3.02144593,3.02259845,3.02374942,3.02489776,3.02601552,3.02710618,3.02819648,3.02927713,3.03035322,3.03140839,3.03245008,3.03347299,3.03445977,3.03541954,3.03627832,3.03712283,3.0379468,3.03875633,3.03954384,3.04032332,3.04109807,3.04184913,3.04257593,3.04329424,3.04400553,3.04470868,3.04540726,3.04610025,3.04678422,3.0474567,3.04812386,3.04878826,3.04943458,3.05007807,3.05070942,3.05132682,3.05193125,3.05253389,3.05313181,3.05372094,3.05430171,3.05488178,3.05543732,3.05597796,3.05650779,3.05703756,3.05756172,3.0580827,3.0586035,3.05912237,3.05960547,3.0600693,3.06051299,3.06095078,3.06138451,3.06181569,3.06224254,3.06266907,3.06309437,3.06351032,3.06391464,3.06431207,3.06470017,3.06508024,3.06545251,3.06582089,3.06616325,3.0664893,3.06681123,3.06710888,3.06739451,3.06767934,3.06795266,3.06821968,3.06847097,3.06871835,3.0689469,3.06917506,3.06940182,3.06961922,3.06982939,3.07003847,3.07023131,3.07041463,3.07059223,3.0707522,3.07090968,3.07104001,3.071138,3.0712274,3.07131636,3.07139369,3.07146714,3.07153993,3.07161179,3.07166394,3.07168854,3.07170775,3.07172281,3.07173572,3.07173595`

python/cpp version:
`0.029074,0.0533635,0.0756559,0.0969472,0.117795,0.138404,0.158655,0.17848,0.197945,0.217106,0.235709,0.25342,0.270723,0.288023,0.305223,0.322026,0.338799,0.355362,0.371411,0.387194,0.402724,0.417815,0.432826,0.447661,0.462446,0.477111,0.491703,0.506267,0.520685,0.535014,0.549245,0.56335,0.57715,0.590934,0.60448,0.61799,0.631494,0.644824,0.658089,0.671308,0.684355,0.697154,0.709899,0.722565,0.735018,0.747461,0.759726,0.771927,0.78406,0.796084,0.808058,0.819925,0.831756,0.843435,0.854981,0.866507,0.877994,0.889435,0.900803,0.912052,0.923281,0.934441,0.94559,0.956563,0.967513,0.978451,0.989377,1.00012,1.01077,1.02142,1.032,1.04254,1.05299,1.06334,1.07366,1.08395,1.0942,1.10442,1.11447,1.1245,1.13447,1.14439,1.15422,1.16389,1.17343,1.18291,1.19235,1.20175,1.21115,1.22054,1.2298,1.23904,1.24827,1.25748,1.26665,1.27575,1.28481,1.29379,1.30272,1.31164,1.32046,1.32924,1.33787,1.34642,1.35494,1.36343,1.37185,1.38024,1.38844,1.39661,1.40477,1.41289,1.42086,1.42877,1.43656,1.44431,1.45201,1.45967,1.46733,1.47496,1.48256,1.49011,1.49763,1.50513,1.51263,1.52005,1.52746,1.53481,1.54216,1.5495,1.5567,1.56389,1.57103,1.57817,1.58531,1.59218,1.59905,1.60589,1.61265,1.61935,1.62605,1.63273,1.63941,1.646,1.65257,1.65908,1.66558,1.67198,1.67836,1.6847,1.69102,1.69734,1.70364,1.70988,1.71606,1.72222,1.72834,1.73444,1.74053,1.74659,1.75263,1.75865,1.76461,1.77057,1.77647,1.78237,1.78824,1.79411,1.7999,1.80566,1.81142,1.81717,1.82271,1.82822,1.83371,1.83916,1.84458,1.84989,1.85519,1.86045,1.86566,1.87086,1.87605,1.88123,1.88639,1.89154,1.8966,1.90161,1.90658,1.91153,1.91643,1.92127,1.92609,1.93088,1.93565,1.94042,1.94513,1.94984,1.95453,1.95921,1.96386,1.96849,1.97311,1.97772,1.98232,1.9869,1.99143,1.99594,2.00045,2.00494,2.00943,2.01388,2.0183,2.02267,2.02703,2.03137,2.03566,2.03993,2.04419,2.04841,2.05262,2.05684,2.06104,2.06523,2.06941,2.07358,2.07773,2.08187,2.08599,2.09011,2.09422,2.09832,2.10231,2.1063,2.11027,2.11422,2.11816,2.12205,2.12591,2.12977,2.13361,2.13742,2.14121,2.14497,2.14873,2.15242,2.15607,2.15967,2.16325,2.16675,2.17023,2.1737,2.17713,2.18052,2.1839,2.18721,2.19051,2.19381,2.19699,2.20017,2.2032,2.2062,2.20919,2.21218,2.21514,2.21808,2.22102,2.22393,2.22682,2.2297,2.23254,2.23533,2.23813,2.2409,2.24366,2.24641,2.24916,2.2519,2.25463,2.25736,2.26008,2.26279,2.2655,2.26817,2.27084,2.2735,2.27615,2.2788,2.28144,2.28403,2.2866,2.28915,2.29169,2.29421,2.29672,2.29922,2.30168,2.30413,2.30658,2.309,2.31142,2.31379,2.31611,2.31843,2.32074,2.32304,2.32533,2.32763,2.32988,2.33212,2.33436,2.33659,2.3388,2.34099,2.34318,2.34536,2.34752,2.34967,2.35175,2.35383,2.35591,2.35798,2.36005,2.36211,2.36416,2.36619,2.36819,2.37019,2.37218,2.37413,2.37608,2.37802,2.37996,2.38188,2.3838,2.3857,2.3876,2.38947,2.39133,2.39316,2.39498,2.39681,2.39861,2.40039,2.40216,2.40392,2.40566,2.40738,2.40911,2.41079,2.41245,2.41411,2.41574,2.41736,2.41898,2.42059,2.42219,2.42378,2.42537,2.42692,2.42844,2.42994,2.43143,2.43292,2.43438,2.43579,2.43719,2.43859,2.43998,2.44134,2.4427,2.44405,2.44539,2.4467,2.44801,2.44928,2.45055,2.45178,2.453,2.45422,2.45544,2.45664,2.45784,2.45903,2.4602,2.46135,2.46243,2.4635,2.46458,2.46562,2.46664,2.46766,2.46864,2.4696,2.47055,2.47148,2.47241,2.47332,2.47423,2.47513,2.47603,2.47692,2.4778,2.47865,2.47951,2.48034,2.48117,2.482,2.48282,2.48362,2.48442,2.48522,2.48602,2.48682,2.4876,2.48838,2.48916,2.48994,2.49071,2.49144,2.49216,2.49288,2.49359,2.49428,2.49494,2.49559,2.49624,2.49687,2.49751,2.49814,2.49876,2.49935,2.49995,2.50052,2.50108,2.50163,2.50216,2.50266,2.50316,2.50365,2.50413,2.5046,2.50507,2.50553,2.50597,2.50641,2.50684,2.50727,2.5077,2.50812,2.50854,2.50896,2.50937,2.50976,2.51013,2.5105,2.51087,2.51123,2.51159,2.51194,2.51226,2.51256,2.51287,2.51316,2.51344,2.51372,2.51399,2.51425,2.51448,2.5147,2.51491,2.51512,2.51533,2.51553,2.51574,2.51594,2.51614,2.51633,2.51652,2.5167,2.51687,2.51704,2.5172,2.51734,2.51747,2.51759,2.5177,2.51779,2.51789,2.51798,2.51806,2.51813,2.5182,2.51826,2.5183,2.51833,2.51835,2.51837,2.51838,2.51839`

these Sv were generated using same MDFS Run function using the following parameters:
in r : `MDFS(data_except_last, last_column$X501, dimensions = 2, divisions = 1,
     range = 0, seed = 0)`

in python: `mdfs.run(data, decision, dimensions = 2, divisions = 1,
     seed = 0, range_ = 0)`

input data used is also attached:  [all_madelon_dat_py.csv](https://github.com/mdfeatureselection/mdfs-py/files/12598205/all_madelon_dat_py.csv)

**Comment by yoctozepto** [comment] 2023-10-14 19:16
Duplicate of #4

**Closed as not planned by yoctozepto** 2023-10-14 19:16 UTC
